services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    container_name: sandbox_postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: sandbox
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - default

volumes:
  data:
