{{- if .Values.sopsSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sandbox-api.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.sopsSecrets}}
  {{ $val.name }}: {{ $val.value | b64enc}}
  {{- end}}  
{{- end }} 
